[doc]
name = "suggestions-for-home-assistant-interactions-that-understand-gestures"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "suggestions-for-home-assistant-interactions-that-understand-gestures"
type = "pdf"
