[doc]
name = 'analysis-of-the-film-the-girl-with-pearl-earrings'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'analysis-of-the-film-the-girl-with-pearl-earrings'
type = 'pdf'
